#!/bin/bash
set -e

# Read secrets from GitHub Actions env
DOCKERHUB_USERNAME="${DOCKERHUB_USERNAME:?Missing DockerHub username}"
DOCKERHUB_TOKEN="${DOCKERHUB_TOKEN:?Missing DockerHub token}"

# Get current Git commit SHA
GIT_SHA=$(git rev-parse HEAD)

echo "🔐 Logging into Docker Hub..."
echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

echo "🔨 Setting up Docker Buildx..."
docker buildx create --use --name multi-builder || echo "Buildx instance already exists"
docker buildx use multi-builder

# Frontend image
echo "📦 Building and pushing Frontend..."
docker buildx build \
  --platform linux/amd64 \
  --file ./frontend/Dockerfile \
  --tag "$DOCKERHUB_USERNAME/frontend:latest" \
  --tag "$DOCKERHUB_USERNAME/frontend:$GIT_SHA" \
  --push \
  ./frontend

# Backend image
echo "📦 Building and pushing Backend..."
docker buildx build \
  --platform linux/amd64 \
  --file ./login-be/Dockerfile \
  --tag "$DOCKERHUB_USERNAME/login-be:latest" \
  --tag "$DOCKERHUB_USERNAME/login-be:$GIT_SHA" \
  --push \
  ./login-be

echo "✅ Done: Docker images pushed to Docker Hub!"
