name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set DockerHub secrets
        run: echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
        shell: bash

      - name: Build & Push Docker Images
        run: |
          chmod +x ./build-and-push.sh
          ./build-and-push.sh

      - name: Update GitOps repo manifests
        run: |
          GIT_SHA=${GITHUB_SHA}
          git clone https://github.com/shinojl4dx/ticket-CD.git /tmp/gitops
          cd /tmp/gitops/apps/ticket-app

          # Update backend image
          sed -i "s#image: .*/login-be:.*#image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/login-be:$GIT_SHA#g" backend-deployment.yaml

          # Update frontend image
          sed -i "s#image: .*/frontend:.*#image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:$GIT_SHA#g" frontend-deployment.yaml

          # Commit & push
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Update Docker images to $GIT_SHA" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shinojl4dx/ticket-CD.git HEAD:main

      - name: Done
        run: echo "✅ CI/CD complete. ArgoCD will deploy automatically."
