name: CI Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      FRONTEND_IMAGE: shinojl4dx/frontend
      LOGIN_BE_IMAGE: shinojl4dx/login-be
      CD_REPO: https://github.com/shinojl4dx/ticket-CD.git
      CD_DIR: /tmp/gitops

    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v3

      - name: Set commit SHA
        id: vars
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t $FRONTEND_IMAGE:$SHA_TAG ./frontend
          docker push $FRONTEND_IMAGE:$SHA_TAG

      - name: Build and push login-be image
        run: |
          docker build -t $LOGIN_BE_IMAGE:$SHA_TAG ./login-be
          docker push $LOGIN_BE_IMAGE:$SHA_TAG

      - name: Clone CD repo
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/shinojl4dx/ticket-CD.git $CD_DIR
          cd $CD_DIR
          git checkout main

      - name: Update manifests with SHA tag
        run: |
          cd $CD_DIR
          # Frontend manifest
          if [ -f frontend-deployment.yaml ]; then
            sed -i "s|\($FRONTEND_IMAGE:\).*|\1$SHA_TAG|g" frontend-deployment.yaml
          fi
          # Login-be manifest
          if [ -f login-be-deployment.yaml ]; then
            sed -i "s|\($LOGIN_BE_IMAGE:\).*|\1$SHA_TAG|g" login-be-deployment.yaml
          fi
          git add .
          git commit -m "Update images to SHA $SHA_TAG"
          git push origin main
