name: CI Build and Update CD Manifests

on:
  push:
    branches: [ main ]

jobs:
  build-and-update-cd:
    runs-on: ubuntu-latest
    steps:
      # -------- Checkout source --------
      - name: Checkout source
        uses: actions/checkout@v4

      # -------- Docker Hub Login --------
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -------- Build & Push Frontend --------
      - name: Build and push Frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${GITHUB_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${GITHUB_SHA}

      # -------- Build & Push Backend --------
      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/login-be:latest ./login-be
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-be:latest
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/login-be:latest ${{ secrets.DOCKERHUB_USERNAME }}/login-be:${GITHUB_SHA}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/login-be:${GITHUB_SHA}

      # -------- Update CD Manifests --------
      - name: Update GitOps CD manifests
        run: |
          echo "🔄 Updating CD manifests with latest image SHA..."
          GIT_SHA=${GITHUB_SHA}
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          # Clone the GitOps repo
          git clone https://github.com/shinojl4dx/ticket-CD.git /tmp/gitops
          cd /tmp/gitops/apps/ticket-app

          # Create backend deployment manifest
          cat > backend-deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-be
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: login-be
          image: docker.io/$DOCKERHUB_USERNAME/login-be:$GIT_SHA
EOF

          # Create frontend deployment manifest
          cat > frontend-deployment.yaml <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          image: docker.io/$DOCKERHUB_USERNAME/frontend:$GIT_SHA
EOF

          # Commit & push changes
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git add .
          git commit -m "Update Docker images to $GIT_SHA" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/shinojl4dx/ticket-CD.git HEAD:main

      - name: Done
        run: echo "✅ CI complete, CD manifests updated. ArgoCD will deploy automatically."
