name: CI Build and Deploy

# Trigger on push to main or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker login secrets
      - name: Set up DockerHub credentials
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Run your build and deploy script
      - name: Build and Deploy
        run: |
          chmod +x ./build-deploy.sh
          ./build-deploy.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
