name: CI Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
      GITOPS_REPO: https://github.com/shinojl4dx/ticket-CD.git
      GITOPS_DIR: /tmp/gitops

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        run: |
          docker build -t shinojl4dx/frontend:${COMMIT_SHA} ./frontend
          docker push shinojl4dx/frontend:${COMMIT_SHA}

      - name: Build and push login-be image
        run: |
          docker build -t shinojl4dx/login-be:${COMMIT_SHA} ./login-be
          docker push shinojl4dx/login-be:${COMMIT_SHA}

      - name: Clone GitOps repo
        run: |
          rm -rf $GITOPS_DIR
          git clone https://x-access-token:${GITOPS_REPO_TOKEN}@github.com/shinojl4dx/ticket-CD.git $GITOPS_DIR
          cd $GITOPS_DIR
          git checkout main

      - name: Update manifests with new SHA
        run: |
          cd $GITOPS_DIR
          # Replace frontend image
          sed -i "s|shinojl4dx/frontend:.*|shinojl4dx/frontend:${COMMIT_SHA}|g" frontend-deployment.yaml
          # Replace login-be image
          sed -i "s|shinojl4dx/login-be:.*|shinojl4dx/login-be:${COMMIT_SHA}|g" login-be-deployment.yaml
          git add .
          git commit -m "Update images to commit ${COMMIT_SHA}"
          git push origin main
