name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: shinojl4dx/frontend
      KUBE_MANIFEST: k8s/frontend.yaml
      GITOPS_REPO: https://github.com/${{ github.actor }}/ticket-CD.git
      GITOPS_DIR: /tmp/gitops

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Tag Docker image with SHA
      id: docker_build
      run: |
        set -e
        SHORT_SHA=$(git rev-parse --short HEAD)
        echo "🔧 Building Docker image with tag $SHORT_SHA..."
        docker build -t $IMAGE_NAME:$SHORT_SHA .
        docker push $IMAGE_NAME:$SHORT_SHA
        echo "IMAGE_TAG=$SHORT_SHA" >> $GITHUB_ENV
        echo "✅ Image pushed: $IMAGE_NAME:$SHORT_SHA"

    - name: Update Kubernetes manifest with SHA tag
      run: |
        echo "🔧 Updating manifest $KUBE_MANIFEST..."
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:${IMAGE_TAG}|" $KUBE_MANIFEST
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add $KUBE_MANIFEST
        git commit -m "ci: update frontend image to $IMAGE_NAME:${IMAGE_TAG}" || echo "No changes to commit"
        git push origin main

    - name: Sync GitOps repo (optional)
      run: |
        echo "🔧 Cloning GitOps repo..."
        git clone https://x-access-token:${{ secrets.GITOPS_REPO_TOKEN }}@github.com/${{ github.actor }}/ticket-CD.git $GITOPS_DIR
        cp $KUBE_MANIFEST $GITOPS_DIR/
        cd $GITOPS_DIR
        git add .
        git commit -m "ci: update frontend image to $IMAGE_NAME:${IMAGE_TAG}" || echo "No changes"
        git push origin main
