name: CI/CD Build & Deploy

on:
  push:
    branches:
      - main

env:
  CI_REPO: ${{ github.repository }}
  CD_REPO: https://github.com/shinojl4dx/ticket-CD.git
  CD_DIR: /tmp/gitops

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout CI repo
      - name: Checkout CI repository
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Compute SHA tag for the commit
      - name: Set image tag
        id: vars
        run: |
          SHA_TAG=$(git rev-parse --short HEAD)
          echo "SHA_TAG=$SHA_TAG" >> $GITHUB_ENV

      # 4️⃣ Build & push frontend image
      - name: Build & push frontend image
        run: |
          docker build -t shinojl4dx/frontend:$SHA_TAG ./frontend
          docker push shinojl4dx/frontend:$SHA_TAG

      # 5️⃣ Build & push login-be image
      - name: Build & push login-be image
        run: |
          docker build -t shinojl4dx/login-be:$SHA_TAG ./login-be
          docker push shinojl4dx/login-be:$SHA_TAG

      # 6️⃣ Checkout CD repo
      - name: Checkout CD repository
        env:
          GITOPS_REPO_TOKEN: ${{ secrets.GITOPS_REPO_TOKEN }}
        run: |
          git clone https://x-access-token:${GITOPS_REPO_TOKEN}@github.com/shinojl4dx/ticket-CD.git $CD_DIR
          cd $CD_DIR
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # 7️⃣ Update manifest files with SHA tags
      - name: Update manifests
        run: |
          cd $CD_DIR
          sed -i "s|\(shinojl4dx/frontend:\).*|\1$SHA_TAG|g" frontend-deployment.yaml
          sed -i "s|\(shinojl4dx/login-be:\).*|\1$SHA_TAG|g" login-be-deployment.yaml

      # 8️⃣ Commit & push updated manifests
      - name: Commit and push changes
        run: |
          cd $CD_DIR
          git add frontend-deployment.yaml login-be-deployment.yaml
          git commit -m "Update images to $SHA_TAG"
          git push origin main

      # 9️⃣ Optional: trigger ArgoCD sync if needed
      - name: Trigger ArgoCD sync
        run: |
          curl -X POST -k \
          -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
          https://argocd.example.com/api/v1/applications/ticket-app/sync
