name: CI Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image SHA
        run: |
          IMAGE_TAG=$(git rev-parse --short HEAD)
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t shinojl4dx/frontend:${IMAGE_TAG} .

      - name: Push Docker image
        run: |
          docker push shinojl4dx/frontend:${IMAGE_TAG}

      - name: Clone GitOps repo
        run: |
          git clone https://x-access-token:${GITOPS_REPO_TOKEN}@github.com/${GITHUB_ACTOR}/ticket-CD.git /tmp/gitops

      - name: Update Kubernetes manifest
        run: |
          sed -i "s|PLACEHOLDER_SHA|${IMAGE_TAG}|g" /tmp/gitops/k8s/frontend-deployment.yaml
          cd /tmp/gitops
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add k8s/frontend-deployment.yaml
          git commit -m "ci: update frontend image to SHA ${IMAGE_TAG}"
          git push
