name: CI Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: shinojl4dx/frontend

    steps:
    # 1️⃣ Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Git
    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    # 3️⃣ Login to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # 4️⃣ Build Docker image
    - name: Build Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        echo "Building image $IMAGE_NAME:$IMAGE_TAG"
        docker build -t $IMAGE_NAME:$IMAGE_TAG .

    # 5️⃣ Push Docker image
    - name: Push Docker image
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        docker push $IMAGE_NAME:$IMAGE_TAG

    # 6️⃣ Update Kubernetes manifest with new image SHA
    - name: Update Kubernetes manifest
      run: |
        IMAGE_TAG=${GITHUB_SHA::8}
        echo "Updating k8s manifest with image tag $IMAGE_TAG"
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:$IMAGE_TAG|g" k8s/frontend-deployment.yaml

    # 7️⃣ Commit and push manifest change back to repo
    - name: Commit updated manifest
      run: |
        git add k8s/frontend-deployment.yaml
        git commit -m "Update frontend image to $GITHUB_SHA"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
